## Upstream Data

### Data

In [ ]:
%load_ext sql

In [20]:
%%sql
{{ open('setup.sql').read() }}

Running query in 'postgresql://dataengineer:***@postgres:5432/ecommerce'

In [ ]:
%sql postgresql://dataengineer:datapipeline@postgres:5432/ecommerce

In [22]:
%%sql
SELECT
  *
FROM
  customer

Running query in 'postgresql://dataengineer:***@postgres:5432/ecommerce'

3 rows affected.

            customer_id                           email                full_name             phone            status                    created_at                              updated_at
c8653895-793e-4120-aa12-6c2919df32f8        alice@example.com        Alice Johnson        +1-555-0101         active         2026-04-12 22:09:21.680152+00:00        2026-04-14 22:09:21.680152+00:00
5eee455b-28d0-42b1-ab0e-52b1cd9ebe74         bob@example.com          Bob Martinez        +1-555-0202         active         2026-04-21 22:09:21.680152+00:00        2026-04-21 22:09:21.680152+00:00
63b43e26-6259-44eb-b084-8cbfb93ecfad        carol@example.com          Carol Kim              None           inactive        2026-04-22 22:09:21.680152+00:00        2026-04-22 22:09:21.680152+00:00

In [ ]:
%%sql
SELECT
  *
FROM
  orders

### ERD

```mermaid
erDiagram
  direction LR
  customer {
    UUID customer_id PK
    VARCHAR email
    VARCHAR full_name
    VARCHAR phone
    VARCHAR status
    TIMESTAMPTZ created_at
    TIMESTAMPTZ updated_at
  }
  orders {
    UUID order_id PK
    UUID customer_id FK
    UUID shipping_addr_id FK
    UUID billing_addr_id FK
    VARCHAR status
    NUMERIC total_amount
    TIMESTAMPTZ placed_at
    TIMESTAMPTZ created_at
    TIMESTAMPTZ updated_at
  }
  customer ||--o{ orders : "places"
```

### What Is Referential Integrity and Why It Matters

In [18]:
%%sql
INSERT INTO
  orders (
    order_id,
    customer_id,
    shipping_addr_id,
    billing_addr_id,
    status,
    total_amount,
    placed_at,
    created_at,
    updated_at
  )
VALUES
  (
    '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000001', -- Non existent customer
    '00000000-0000-0000-0000-000000000002',
    '00000000-0000-0000-0000-000000000003',
    'pending',
    99.99,
    now (),
    now (),
    now ()
  );

Running query in 'postgresql://dataengineer:***@postgres:5432/ecommerce'

RuntimeError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "orders" violates foreign key constraint "orders_customer_id_fkey"
DETAIL:  Key (customer_id)=(00000000-0000-0000-0000-000000000001) is not present in table "customer".

[SQL: INSERT INTO
  orders (
    order_id,
    customer_id,
    shipping_addr_id,
    billing_addr_id,
    status,
    total_amount,
    placed_at,
    created_at,
    updated_at
  )
VALUES
  (
    '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000001',
    '00000000-0000-0000-0000-000000000002',
    '00000000-0000-0000-0000-000000000003',
    'pending',
    99.99,
    now (),
    now (),
    now ()
  );]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

## Data Pipelines and Warehouses Usually Ignore Relationships

In [21]:
# pull data from postgres -> csv -> DuckDB
import duckdb
from datetime import datetime, timedelta, timezone

now = datetime.now(timezone.utc) - timedelta(hours=1)

daily_run_ts  = now.replace(hour=0, minute=0, second=0, microsecond=0).strftime("%Y-%m-%d %H:%M:%S")
hourly_run_ts = now.strftime("%Y-%m-%d %H:%M:%S")

con = duckdb.connect()
con.execute("INSTALL postgres; LOAD postgres;")
con.execute("""
    ATTACH 'dbname=ecommerce user=dataengineer password=datapipeline host=postgres port=5432' 
    AS pg (TYPE postgres);
""")

print(f"Pulling customer data until {daily_run_ts}")
con.execute(f"""
    CREATE TABLE customer AS 
    SELECT * FROM pg.customer
    WHERE updated_at <= '{daily_run_ts}';
""")

print(f"Pulling orders data until {hourly_run_ts}") # Fact data is typically loaded into the warehouse more frequently
con.execute(f"""
    CREATE TABLE orders AS 
    SELECT * FROM pg.orders
    WHERE created_at >= '{hourly_run_ts}';
""")

for table in ['customer', 'orders']:
    count = con.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
    print(f"{table}: {count} rows")

display(con.execute("select * from customer").fetch_df())
display(con.execute("select * from orders").fetch_df())

Pulling customer data until 2026-04-22 00:00:00
Pulling orders data until 2026-04-22 21:09:24
customer: 2 rows
orders: 4 rows

,customer_id,email,full_name,phone,status,created_at,updated_at
0,c8653895-793e-4120-aa12-6c2919df32f8,alice@example.com,Alice Johnson,+1-555-0101,active,2026-04-12 22:09:21.680152+00:00,2026-04-14 22:09:21.680152+00:00
1,5eee455b-28d0-42b1-ab0e-52b1cd9ebe74,bob@example.com,Bob Martinez,+1-555-0202,active,2026-04-21 22:09:21.680152+00:00,2026-04-21 22:09:21.680152+00:00

,order_id,customer_id,shipping_addr_id,billing_addr_id,status,total_amount,placed_at,created_at,updated_at
0,0d1ed313-e1eb-4228-bc04-04452d0a3091,c8653895-793e-4120-aa12-6c2919df32f8,65d0c705-53f6-4fe4-a6ec-f4b7ee31e575,65d0c705-53f6-4fe4-a6ec-f4b7ee31e575,delivered,129.99,2026-04-19 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00
1,9d3add68-0532-4558-a875-4658f9cc3bf0,c8653895-793e-4120-aa12-6c2919df32f8,79f5af30-e10d-49ae-bc8f-7b008b8eb463,65d0c705-53f6-4fe4-a6ec-f4b7ee31e575,processing,54.00,2026-04-19 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00
2,3011f8be-9cd5-46a9-823f-fa8e4edb2dc4,5eee455b-28d0-42b1-ab0e-52b1cd9ebe74,5a60ee19-5fc2-4e41-9c38-23543cb05c63,5a60ee19-5fc2-4e41-9c38-23543cb05c63,shipped,249.50,2026-04-21 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00
3,f94d6af1-4f9d-4737-aa9d-34c9ca60eca7,63b43e26-6259-44eb-b084-8cbfb93ecfad,cdb0c9ad-f1d0-4dc6-9f32-21f0511e61af,cdb0c9ad-f1d0-4dc6-9f32-21f0511e61af,pending,75.00,2026-04-22 21:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00

In [23]:
# Orphaned records
con.execute("""
select o.customer_id
from orders o
left join customer c 
on o.customer_id = c.customer_id
where c.customer_id is null
group by 1
""").fetch_df()

                            customer_id
0  63b43e26-6259-44eb-b084-8cbfb93ecfad

In [24]:
con.execute("""
SELECT o.*
, c.full_name
, c.email
FROM orders o
JOIN customer c 
on o.customer_id = c.customer_id
""").fetch_df()

,order_id,customer_id,shipping_addr_id,billing_addr_id,status,total_amount,placed_at,created_at,updated_at,full_name,email
0,0d1ed313-e1eb-4228-bc04-04452d0a3091,c8653895-793e-4120-aa12-6c2919df32f8,65d0c705-53f6-4fe4-a6ec-f4b7ee31e575,65d0c705-53f6-4fe4-a6ec-f4b7ee31e575,delivered,129.99,2026-04-19 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00,Alice Johnson,alice@example.com
1,9d3add68-0532-4558-a875-4658f9cc3bf0,c8653895-793e-4120-aa12-6c2919df32f8,79f5af30-e10d-49ae-bc8f-7b008b8eb463,65d0c705-53f6-4fe4-a6ec-f4b7ee31e575,processing,54.00,2026-04-19 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00,Alice Johnson,alice@example.com
2,3011f8be-9cd5-46a9-823f-fa8e4edb2dc4,5eee455b-28d0-42b1-ab0e-52b1cd9ebe74,5a60ee19-5fc2-4e41-9c38-23543cb05c63,5a60ee19-5fc2-4e41-9c38-23543cb05c63,shipped,249.50,2026-04-21 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00,Bob Martinez,bob@example.com

In [25]:
con.execute("""
SELECT COALESCE(c.full_name, 'UNKNOWN') as full_name
, COALESCE(c.email, 'UNKNOWN') as email
, o.*
FROM orders o
LEFT JOIN customer c 
on o.customer_id = c.customer_id
""").fetch_df()

,full_name,email,order_id,customer_id,shipping_addr_id,billing_addr_id,status,total_amount,placed_at,created_at,updated_at
0,Alice Johnson,alice@example.com,0d1ed313-e1eb-4228-bc04-04452d0a3091,c8653895-793e-4120-aa12-6c2919df32f8,65d0c705-53f6-4fe4-a6ec-f4b7ee31e575,65d0c705-53f6-4fe4-a6ec-f4b7ee31e575,delivered,129.99,2026-04-19 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00
1,Alice Johnson,alice@example.com,9d3add68-0532-4558-a875-4658f9cc3bf0,c8653895-793e-4120-aa12-6c2919df32f8,79f5af30-e10d-49ae-bc8f-7b008b8eb463,65d0c705-53f6-4fe4-a6ec-f4b7ee31e575,processing,54.00,2026-04-19 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00
2,Bob Martinez,bob@example.com,3011f8be-9cd5-46a9-823f-fa8e4edb2dc4,5eee455b-28d0-42b1-ab0e-52b1cd9ebe74,5a60ee19-5fc2-4e41-9c38-23543cb05c63,5a60ee19-5fc2-4e41-9c38-23543cb05c63,shipped,249.50,2026-04-21 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00
3,UNKNOWN,UNKNOWN,f94d6af1-4f9d-4737-aa9d-34c9ca60eca7,63b43e26-6259-44eb-b084-8cbfb93ecfad,cdb0c9ad-f1d0-4dc6-9f32-21f0511e61af,cdb0c9ad-f1d0-4dc6-9f32-21f0511e61af,pending,75.00,2026-04-22 21:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00,2026-04-22 22:09:21.680152+00:00

## Your Options: 100% RI Compliance, UNKNOWN Columns Ok, or Something in Between

In [26]:
failure_query = """
SELECT o.customer_id
FROM orders o
LEFT JOIN customer c ON o.customer_id = c.customer_id
WHERE c.customer_id IS NULL
"""

# if the failure query returns rows => RI failed
failure_rows = con.execute(failure_query).fetchall()

if len(failure_rows) > 0:
    print("Referential Integrity Test Failed...")
    print(f"Failed order's customer_ids {failure_rows}")

Referential Integrity Test Failed...
Failed order's customer_ids [(UUID('63b43e26-6259-44eb-b084-8cbfb93ecfad'),)]

This is what [dbt relationship tests](https://docs.getdbt.com/reference/resource-properties/data-tests?version=1.11#relationships) do under the hood.

In [27]:
failure_threshold = 0.30 # no more than 30% rows violating RI or 70% of rows conforming to RI

failure_query = f"""
With count_metrics as (
SELECT count(o.customer_id) as total_cnt
, count(c.customer_id) as matching_cnt
FROM orders o
LEFT JOIN customer c ON o.customer_id = c.customer_id)
select total_cnt
, matching_cnt
, ((total_cnt - matching_cnt)*1.0)/total_cnt as missing_percentage
, case when missing_percentage > {failure_threshold} then 'FAILED' else 'PASSED' end as RI_check
from count_metrics
"""

con.execute(failure_query).fetch_df()

   total_cnt  matching_cnt  missing_percentage RI_check
0          4             3                0.25   PASSED